### ISSUE TITLE
Adjust layout for content pages

### ISSUE THREAD

**Issue by ClemCB** [womenhackfornonprofits/together-in-the-uk#11]
Once design is ready, the design for three (initially) content pages is required. Wireframe to be created.

Three pages to be:
- [x] Accommodation
- [x] Work
- [x] Money

**Comment by VAO11** [comment]
Are wireframes required for each page?
Should this issue be split into smaller tasks?

**Comment by lili2311** [comment]
For go live we only have 2 page types, homepage and information topic page. We already have homepage wireframe but with minor alterations and the info page type could do with a quick wireframe but the content we have kind if already gives it a shape. Maybe how we show links at the bottom could be considered.

**Comment by VAO11** [comment]
@lili2311 uploaded content onto the 3 pages.
