### ISSUE TITLE
Child theme seems to have broken the subpage content it is not displaying correctly

### ISSUE THREAD

**Issue by lili2311** [womenhackfornonprofits/together-in-the-uk#14]
http://dev-together-in-the-uk.pantheonsite.io/accomodation/ >> I added content yet we cannot see it, please investigate I suspect the child theme is at fault.

**Comment by VAO11** [comment]
Hi @lili2311, I had a look the content. It was the gallery classes that you added around the div tags, which stopped the content from displaying correctly. A template is yet to be created for the content pages (issue #11), so no css styling yet. The Gallery styling is from the original sparkling theme.

I have removed the class for now, the content is showing as expected.

**Comment by VAO11** [comment]
This issue has been resolved.
