### ISSUE TITLE
Add content for Health

### ISSUE THREAD

**Issue by lili2311** [womenhackfornonprofits/together-in-the-uk#17]
- [ ] Grab the intro and the what is in this section from [Category

 Intro](https://drive.google.com/drive/u/0/folders/0Bw1aIZcuiBCXejB1UkZENEpjZWM)

- [ ] Then add in the content form here, please don't duplicate the quotes[Content

 for Health](https://drive.google.com/drive/u/0/folders/0Bw1aIZcuiBCXejB1UkZENEpjZWM)
- [ ] This is the page to update http://dev-together-in-the-uk.pantheonsite.io/wp-admin/post.php?post=192&action=edit

**Comment by sandyho87** [comment]
heya, i can't access the CMS in wordpress- let me know what I need to do? 

thanks!

**Comment by lili2311** [comment]
is this access sorted now?

**Comment by sandyho87** [comment]
yes, apologies for going MIA, busy week. will get it loaded this weekend =)
