### ISSUE TITLE
Add content for Daily Life

### ISSUE THREAD

**Issue by lili2311** [womenhackfornonprofits/together-in-the-uk#18]
- [x] Grab the intro and the what is in this section from [Daily Life

 Intro](https://drive.google.com/drive/u/0/folders/0Bw1aIZcuiBCXejB1UkZENEpjZWM)

- [x] Then add in the content form here, please don't duplicate the quotes[Content

 for Daily Life](https://drive.google.com/drive/u/0/folders/0Bw1aIZcuiBCXejB1UkZENEpjZWM)
- [] This is the page to update http://dev-together-in-the-uk.pantheonsite.io/wp-admin/post.php?post=194&action=edit

**Comment by ankanyuza** [comment]
Content has been added but the content styling is not complete yet. I will try to complete this by this evening.

**Comment by lili2311** [comment]
👍
