### ISSUE TITLE
Populate the Contact Us Page

### ISSUE THREAD

**Issue by VAO11** [womenhackfornonprofits/together-in-the-uk#22]
#Create a contact us page:

**Required fields**
- Tel Number
- Email form with categories. Generate the list of categories from wordpress

- [x] Test [Contact Us Plug-ins](https://www.codeinwp.com/blog/best-contact-form-plugins-wordpress/) - *Sparkling Theme optimised for ```Contact Form 7``` and ```Jetpack```*

- [x] Create Custom Form funtionality to Child theme   **```PHP```** **```HTML```** ***(Optional)***
- [ ] Check with TGIUK to confirm their preference
- [ ] Set the contact to agree email address

**Comment by lili2311** [comment]
@ankanyuza Are you finished with this? There are some tweaks I can wee we can make with CSS if you are done with the functionality do you mind if I tweak the CSS to tidy up for go live?

**Comment by lili2311** [comment]
Styles tweaked and added a short intro sentence.
