### ISSUE TITLE
change blockquotes to speech bubble

### ISSUE THREAD

**Issue by VAO11** [womenhackfornonprofits/together-in-the-uk#36]
- [x] Change content blockquotes to speech bubbles
- [ ] Change text colour from green to navy blue in blockquotes

**Comment by VAO11** [comment]
Hey @ankanyuza, could you please push your speech bubbles to the live (dev) site so that TGIUK can review it. I think we can add more formatting once we get feedback.

![image](https://cloud.githubusercontent.com/assets/20387843/23544874/ad775f5c-fff0-11e6-8335-d5e4c2e371b2.png)

Let me know if you require anything.

**Comment by ankanyuza** [comment]
The change has been done on daily life page for review purposes

**Comment by VAO11** [comment]
Hi @ankanyuza, Teresa is happy with the speech bubble. Can you please update the style.css so your speech bubble affects all blockquotes as is the case currently.

Link it to the original custom-category blockquote classes.

**Comment by lili2311** [comment]
These look great on all pages, so I would say this is done and will close the ticket. If you think it should be re-opened please feel free to comment.
