### ISSUE TITLE
All team members to be signed up on Pantheon & Kalabox

### ISSUE THREAD

**Issue by ClemCB** [womenhackfornonprofits/together-in-the-uk#8]
We're using Pantheon to host the TGIUK website: https://pantheon.io/features/developer-dashboard

To get signed up ask for log in details from Lilli.

Kalabox is the recommended platform to allow us to deploy the site on Pantheon: http://www.kalabox.io/

Any problems signing up to this see Pantheon local development docs.

- [x]  Lili
- [x] Kasia
- [ ] Clem
- [x] Victoria
- [ ] Yana
- [x] Cigdem

**Comment by ghost** [comment]
got Pantheon and MAMP
