### ISSUE TITLE
Initial theme to be committed

### ISSUE THREAD

**Issue by ClemCB** [womenhackfornonprofits/together-in-the-uk#9]
TGIUK have requested we use Sparkling as the website theme: https://colorlib.com/sparkling/

Colours etc to be edited at a later date.

**Comment by VAO11** [comment]
@lili2311  Sparkling theme has been uploaded to pantheon. It still needs to be activated on the dev wordpress.

**Comment by VAO11** [comment]
@ClemCB @lili2311 @kpranke - The sparkling theme has been activated now.
